package com.hzw.fdc.scalabean

case class ControlPlanInfo(locationId:String,
                           locationName:String,
                           moduleId:String,
                           moduleName:String,
                           toolName:String,
                           toolId:String,
                           chamberName:String,
                           chamberId:String,
                           recipeName: String,
                           recipeId:String,
                           productName:String,
                           stageName:String,
                           controlPlanId:Long,
                           toolGroupId:String,
                           toolGroupName:String,
                           toolGroupVersion:String,
                           chamberGroupId:String,
                           chamberGroupName: String,
                           chamberGroupVersion:String,
                           recipeGroupId:String,
                           recipeGroupName:String,
                           recipeGroupVersion:String,
                           limitStatus:String,
                           area:String,
                           section:String,
                           mesChamberName:String
                           )
